print("Welcome to the tip calculator!")
bill=float(input("what was the bill ?"))
tip=int(input("How much tip would you like to give? 10, 12, or 15?"))
split=float(input("How many people to split the bill?"))
total = bill +(bill*tip/100)
amount_per_person= str(total /split)
print("Each person should pay:" + amount_per_person)